### PR TITLE
Update lua paths

### PR DESCRIPTION
**Pull request by klen**
Hello, I'm a mac user (and I'm not familiar with Lua). On Mac, I've installed Lua from homebrew and by default, it has version 5.4. I had a bunch of errors with the package because of `package.path`. The commit fixes the errors for users like me.

### CODE REVIEW

**Comment by notomo** [comment]
@klen 
Thank you for your contribution.

Looks good to me, but I'd like to know the problem accurately.
Could you show me the following commands output?

- `luarocks --version`
- `luarocks config`
- `nvim --headless -u NORC +"lua print(_VERSION)" +quit`
- `luarocks which vusted.run`
- `luarocks --lua-version=5.1 which vusted.run`

**Comment by klen** [comment]
Sure:

```
$ luarocks --version
/usr/local/bin/luarocks 3.8.0
LuaRocks main command-line interface
```

```
$ luarocks config
accept_unknown_fields = false
arch = "macosx-x86_64"
cache = {
   luajit_version_checked = true
}
cache_fail_timeout = 86400
cache_timeout = 60
check_certificates = false
cmake_generator = "Unix Makefiles"
config_files = {
   nearest = "/usr/local/etc/luarocks/config-5.4.lua",
   system = {
      file = "/usr/local/etc/luarocks/config-5.4.lua",
      found = true
   },
   user = {
      file = "/Users/horneds/.luarocks/config-5.4.lua",
      found = false
   }
}
connection_timeout = 30
deploy_bin_dir = "/usr/local/bin"
deploy_lib_dir = "/usr/local/lib/lua/5.4"
deploy_lua_dir = "/usr/local/share/lua/5.4"
deps_mode = "one"
disabled_servers = {}
export_path_separator = ":"
external_deps_dirs = {
   "/usr/local",
   "/usr",
   "/"
}
external_deps_patterns = {
   bin = {
      "?"
   },
   include = {
      "?.h"
   },
   lib = {
      "lib?.a",
      "lib?.so",
      "lib?.so.*"
   }
}
external_deps_subdirs = {
   bin = "bin",
   include = "include",
   lib = "lib"
}
external_lib_extension = "dylib"
fs_use_modules = true
gcc_rpath = true
home = "/Users/horneds"
home_tree = "/Users/horneds/.luarocks"
homeconfdir = "/Users/horneds/.luarocks"
hooks_enabled = true
lib_extension = "so"
lib_modules_path = "/lib/lua/5.4"
link_lua_explicitly = false
local_by_default = false
local_cache = "/Users/horneds/.cache/luarocks"
lua_extension = "lua"
lua_found = {
   lua_bindir = "/usr/local/opt/lua/bin",
   lua_dir = "/usr/local/opt/lua",
   lua_interpreter = "lua5.4",
   lua_version = "5.4"
}
lua_interpreter = "lua5.4"
lua_modules_path = "/share/lua/5.4"
lua_version = "5.4"
major_version = "3.8"
no_manifest = false
obj_extension = "o"
processor = "x86_64"
program_series = "3.8"
program_version = "3.8.0"
rocks_dir = "/usr/local/lib/luarocks/rocks-5.4"
rocks_servers = {
   {
      "https://luarocks.org",
      "https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/",
      "https://luafr.org/luarocks/",
      "http://luarocks.logiceditor.com/rocks"
   }
}
rocks_subdir = "/lib/luarocks/rocks-5.4"
rocks_trees = {
   {
      name = "user",
      root = "/Users/horneds/.luarocks"
   },
   {
      name = "system",
      root = "/usr/local"
   }
}
runtime_external_deps_patterns = {
   bin = {
      "?"
   },
   include = {
      "?.h"
   },
   lib = {
      "lib?.so",
      "lib?.so.*"
   }
}
runtime_external_deps_subdirs = {
   bin = "bin",
   include = "include",
   lib = "lib"
}
static_lib_extension = "a"
sysconfdir = "/usr/local/etc/luarocks"
target_cpu = "x86_64"
upload = {
   api_version = "1",
   server = "https://luarocks.org",
   tool_version = "1.0.0"
}
user_agent = "LuaRocks/3.8.0 macosx-x86_64"
variables = {
   AR = "ar",
   BUNZIP2 = "bunzip2",
   CC = "env MACOSX_DEPLOYMENT_TARGET=10.8 gcc",
   CFLAGS = "-O2 -fPIC",
   CHMOD = "chmod",
   CMAKE = "cmake",
   CP = "cp",
   CURL = "curl",
   CURLNOCERTFLAG = "-k",
   CVS = "cvs",
   FIND = "find",
   GIT = "git",
   GPG = "gpg",
   GUNZIP = "gunzip",
   HG = "hg",
   ICACLS = "icacls",
   LD = "env MACOSX_DEPLOYMENT_TARGET=10.8 gcc",
   LIBFLAG = "-bundle -undefined dynamic_lookup -all_load",
   LIB_EXTENSION = "so",
   LS = "ls",
   LUA = "/usr/local/opt/lua/bin/lua5.4",
   LUALIB = "liblua5.4.dylib",
   LUA_BINDIR = "/usr/local/opt/lua/bin",
   LUA_DIR = "/usr/local/opt/lua",
   LUA_INCDIR = "/usr/local/opt/lua/include/lua5.4",
   LUA_LIBDIR = "/usr/local/opt/lua/lib",
   LUA_LIBDIR_FILE = "liblua5.4.dylib",
   MAKE = "make",
   MD5 = "md5",
   MD5SUM = "md5sum",
   MKDIR = "mkdir",
   MKTEMP = "mktemp",
   OBJ_EXTENSION = "o",
   OPENSSL = "openssl",
   PWD = "pwd",
   RANLIB = "ranlib",
   RM = "rm",
   RMDIR = "rmdir",
   ROCKS_TREE = "/usr/local/lib/luarocks/rocks-5.4",
   RSYNC = "rsync",
   RSYNCFLAGS = "--exclude=.git -Oavz",
   SCP = "scp",
   SCRIPTS_DIR = "/usr/local/bin",
   SEVENZ = "7z",
   SSCM = "sscm",
   SVN = "svn",
   TAR = "tar",
   TEST = "test",
   TOUCH = "touch",
   UNZIP = "unzip -n",
   WGET = "wget",
   WGETNOCERTFLAG = "--no-check-certificate",
   ZIP = "zip"
}
web_browser = "open"
wrapper_suffix = ""
```
```
$ nvim --headless -u NONE +"lua print(_VERSION)" +quit
Lua 5.1
```
```
$ luarocks which vusted.run

Error: Module 'vusted.run' not found.
```
```
$ luarocks --lua-version=5.1 which vusted.run
/Users/horneds/.luarocks/share/lua/5.1/vusted/run.lua
(provided by vusted 2.0.0-1)
```

**Comment by klen** [comment]
Actually, the problem was with "*.so" packages. Luarocks builds them for the current Lua version (for mac 5.4), but nvim uses Lua 5.1 (because of luajit) and it doesn't work. So on mac you have to install `vusted` with `luarocks --lua-version=5.1 install vusted` to build correct packages and with the PR, everything starts working fine.

**Comment by notomo** [comment]
Thanks!

reproduced.
```
$ vusted
9 more lines
/usr/local/bin/vusted_entry.vim, line 12
Vim(lua):E5108: Error executing lua /usr/local/share/lua/5.4/pl/path.lua:26: pl.path requires LuaFileSystem
stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.4/pl/path.lua:26: in main chunk
        [C]: in function 'require'
        /usr/local/share/lua/5.4/busted/runner.lua:3: in main chunk
        [C]: in function 'require'
        /usr/local/share/lua/5.4/vusted/run.lua:11: in function </usr/local/share/lua/5.4/vusted/run.lua:1>
        [string ":lua"]:2: in main chunk%
```

**Pull request merged**
